config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"
  patch 'books/:id' => 'books#update',as: 'update_book'

  resources :books, only: [:new, :create, :index, :show, :edit, :destroy]
  resources :users, only: [:show, :edit, :index, :update,]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy       
  has_one_attached :profile_image
  
  validates :name, uniqueness: true,
    length: { minimum: 2, maximum: 20 }
    
  validates :introduction, length: { maximum: 50 }
  
  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user[:id])
  end

  def after_sign_out_path_for(resource)
    '/'
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)

    flash[:notice] = 'You have updated book successfully'
      redirect_to book_path(@book.id)
    else

      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :introduction)
  end

end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated book successfully'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">

  <h2>User info!</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
    </table>

    <div class="row">
      <div class="sccial"></div>
      <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>


    <h2 class="mt-3">New book</h2>

    <% if book.errors.any? %>
      <%= book.errors.count %>errors prohibited this obj from being saved
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

    <%= form_with model: book do |f| %>
      <div class="form-grop">
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div class="form-grop">
        <h4>Opinion</h4>
        <%= f.text_area :body %>
      </div>
      <div class="form-grop">
        <%= f.submit "Create Book", Class: "btn btn-success" %>
      </div>
    <% end %>

</div>

app/views/books/edit.html.erb
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Book</h1>
        
      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
        

        <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

          <h4>Title</h4>
          <%= f.text_field :title %>

          <h4>Opinion</h4>
          <%= f.text_area :body %>

          <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">

        <% end %>


        <%= link_to "Show", book_path(@book.id) %>
          |
        <a class="back" href="/books">Back</a>

      </div>
    </div>
  </div>

app/views/books/index.html.erb
<script src="https://kit.fontawesome.com/a8946225b7.js" crossorigin="anonymous"></script>

<main>


    <div class="container px-5 px-sm-0">
      <div class="row">

        <%= render 'books/book', book:@book, user:current_user  %>



        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>

          <table class="table table-striped">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>

            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(100,100) %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </p>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice">
    <div class="container px-5 px-sm-0">
      <div class="row">

        <%= render 'books/book', book:Book.new, user:@user  %>

        <div class="col-md-8 offset-md-1">
          <h1>Book detail</h1>

          <table class="table">
            <tbody>
              <tr>
                <td>
                  <%= image_tag @book.user.get_profile_image(100,100) %>
                  <br>
                  <%= link_to @book.user.name, user_path(@user.id) %>
                </td>
                <td><%= link_to @book.title %></td>
                <td><%= @book.body %></td>
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book_path" %>
                  <% end %>
                </td>
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </p>
</main>

app/views/homes/about.html.erb
<%= stylesheet_link_tag 'homes' %>
<script src="https://kit.fontawesome.com/a8946225b7.js" crossorigin="anonymous"></script>
  <main>

    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">
          Welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !
        </h1>
      </div>
    </div>
  </main>

app/views/homes/top.html.erb
<%= stylesheet_link_tag 'homes' %>
<script src="https://kit.fontawesome.com/a8946225b7.js" crossorigin="anonymous"></script>

  <div class="sccial"></div>


  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="mx-auto coll-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>
            welcome to

            <i class="fas fa-book"></i>

            <strong>Bookers</strong>
            !!
          </h1>

          <p class="top-text">
            In

            <i class="fas fa-book"></i>

            <strong>Bookers</strong>
            ,
          </p>
          <p class="top-text">
            you can share and exchange your opinions , inpressions , and emotions
          </p>
          <p class="top-text">
            about various books!
          </p>

          <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
              </div>
              <div class="row">
                <a class="btn btn-success btn-sm btn-block mb-3 sign_up" href="/users/sign_up">Sign up</a>
              </div>
          </div>

        </div>
      </div>
    </div>
  </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a8946225b7.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header>
      <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <biiton class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </biiton>
        <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
          <ul class="navbar-nav ml-auto">


            <div class="sccial"></div>

          <% if user_signed_in? %>
            <div class="nav-list-item">
              <li>
                <%= link_to user_path(current_user.id) do %>
                 <i class="fas fa-home"></i>Homes
                <% end %>
              </li>
            </div>
            <div class="nav-list-item">
              <li>
                <%= link_to "/users" do %>
                  <i class="fas fa-users"></i>Users
                <% end %>
              </li>
            </div>
            <div class="nav-list-item">
              <li>
                <%= link_to '/books' do %>
                  <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
            </div>
            <div class="nav-list-item">
              <li>
                <%= link_to  destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>Log out
                <% end %>
            </div>





          <div class="navgation">
          <% else %>

            <div class="nav-list-item">
              <li>
                <%= link_to "/" do %>
                <i class="fas fa-home"></i>Homes
                <% end %>
              </li>
            </div>
            <div class="nav-list-item">
              <li>
                <%= link_to about_path  do %>
                <i class="fas fa-link"></i>About
                <% end %>
              </li>
            </div>
            <div class="nav-list-item">
              <li>
                <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
            </div>
            <div class="nav-list-item">
              <li>
                <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
            </div>
          </div>


          <% end %>

          </ul>
        </div>
        </div>
      </div>


    </header>


    <main>


      <div class="text-success">
        <%= flash[:notice] %>
      </div>
      <div class="text-danger">
        <%= flash[:alret] %>
      </div>

      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
  
 
    <div class="error_explanation">
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>  
   

  <div class="container">
    <div class="row">
      <div class="col-sm-15 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user do |f| %>

          <div class="form-group">
            <lable for="inputName">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
          </div>

          <div class="form-group">
            <label for="inputIntroduction">introduction</label>
            <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"説明"%>
          </div>

          <div class="form-group">
            <label for="inputImage">Image</label>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>

          <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-dasable-with="Update User">

        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<script src="https://kit.fontawesome.com/a8946225b7.js" crossorigin="anonymous"></script>

<main>
  <p id="notice">
    <div class="container px-5 px-sm-0">
      <div class="row">
          
        <%= render 'books/book', book:Book.new, user:@user  %>

        <div class="col-md-8 offset-md-1">
        <h1>Users</h1>

          <table class="table table-striped">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= image_tag user.get_profile_image(100,100)%></td>
                  <td><%= user.name %></td>
                  <td><%= link_to "Show", user %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </p>
</main>

app/views/users/show.html.erb
<script src="https://kit.fontawesome.com/a8946225b7.js" crossorigin="anonymous"></script>

<main>
  <p id="notice">
    <div class="container px-5 px-sm-0">
      <div class="row">
        
        <%= render 'books/book', book:@book, user:@user %>

        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>

          <table class="table table-striped">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>

            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to @user do %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %>
                </td>
                <td><%= book.body %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </p>
</main>